### ISSUE TITLE
CallBack Function Not Working and Scope not pass in uri

### ISSUE THREAD

**Issue by wmtjaychhatrola** [patelmayankce/react-apple-login#1]
```
<AppleLogin
                          scope="email name"
                          clientId='XYZ'
                          redirectURI="https://xyz.com"
                          callback={response => console.log(response)}
                          render={({ onClick }) => (
                            <Button
                              className="text-medium connect-with-btn apple"
                              onClick={onClick}
                              disabled={disableButton}
                              size="large"
                            >
                              <span>Continue with Apple</span>
                            </Button>
                          )}
                        />
```

**Comment by patelmayankce** [comment]
Hi @wmtjaychhatrola 
Thanks for checking out the react-apple-login.

1) Callback will only work with `response_type=query`.
2) Scope also not work with `response_type=query`, if you change value to `form_post` or `fragment` it will work.

You can play it around here. https://patelmayankce.github.io/react-apple-login.

Sorry for not mentioning the callback on the document. I will add these things in README.

**Comment by wmtjaychhatrola** [comment]
Thanks for a quick response
i try your solution also but can't work callback function.
I can't get any type of response data.

**Comment by patelmayankce** [comment]
@wmtjaychhatrola, could you share client id and redirect URL?

**Comment by jacky-ew** [comment]
how to resolve `form_post` bro

**Comment by Vinh127** [comment]
> @wmtjaychhatrola, could you share client id and redirect URL?

Hi bro, i got an issue that when i  login with Apple, i also receive the data in the first click button, but at the 2nd time when i click i receive a message that's  "Your request could not be completed because of an error. Please try again later." . So, can you show me how to fix this issue bro

**Comment by rushinariya29** [comment]
@Vinh127 

I got the same issue.
Have you found any solution or is there any way to fix this error?
