### ISSUE TITLE
How to request for both id_token and code?

### ISSUE THREAD

**Issue by jacky-ew** [patelmayankce/react-apple-login#10]
> The type of response requested. Valid values are code and id_token. You can request one or both.

May i know what to put into `responsType` props if i needed both code and idToken?

**Comment by jacky-ew** [comment]
is it possible to include the callback object? like so
`{
     "authorization": {
       "state": "[STATE]",
       "code": "[CODE]",
       "id_token": "[ID_TOKEN]"
     },
     "user": {
       "email": "[EMAIL]",
       "name": {
         "firstName": "[FIRST_NAME]",
         "lastName": "[LAST_NAME]"
       }
     }
}`

**Comment by anunes9** [comment]
@jacky-ew Try this code, worked for me
```
<AppleLogin
  clientId="react.client.id"
  redirectURI="http://redirect.url"
  responseMode="fragment"
  responseType="code id_token"
/>
```

**Comment by patelmayankce** [comment]
@jacky-ew , Thanks for the feedback!!,

Callback object added in the document.
