### ISSUE TITLE
facebook login triggers Apple Login callback

### ISSUE THREAD

**Issue by chin2km** [patelmayankce/react-apple-login#12]
Apple login callback is triggered if the window.location url params include `code` query. 
But Facebook also adds a `code` query to the FB login callback url. Thus Apple login callback gets triggered when you login successfully with FB login button.

**Comment by patelmayankce** [comment]
@chin2km , yeah you are right. Actually FB & Apple both use the same query parameter which is code. And in Apple, we only have a way to trigger callback which is code in query parameter.

**Comment by pantelispanayiotou** [comment]
are there any workarounds?

**Comment by patelmayankce** [comment]
@chin2km @pantelispanayiotou you guys can use the latest version which have the option `usePopup` to avoid this issue.
