### ISSUE TITLE
What can do next with the "code" which is gotten from Apple?

### ISSUE THREAD

**Issue by hiep294** [patelmayankce/react-apple-login#14]
Hi Mayank Patel, 
After sign in with Apple successfully, it will redirect to the redirectURL with the "code" in query. What should can I do next?, (The Api requires the following info to complete sign in with apple: token, name)
![ddddd](https://user-images.githubusercontent.com/46871089/91277504-1ec7f200-e7ad-11ea-8d04-8f04dbf26c1e.png)

**Comment by patelmayankce** [comment]
@hiep294 you can follow this link 
https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple#create-a-private-key-for-client-authentication

**Comment by ohpyupi** [comment]
@hiep294 The code can be exchanged for access token if you want to access Apple service on behalf of users. If you just want to authenticate a user by Sign in with Apple, you can pass id_token to the parameter `responseType`.

On receiving id token, you can validate if the id token is indeed signed by Apple. If the id token is a legit one, based on the auth context, you can either register the user in your service or login the user.

**Comment by anishbishnoi127** [comment]
i will try
