### ISSUE TITLE
Getting "invalid_request  Invalid response type" error while making responseType={"id_token"}

### ISSUE THREAD

**Issue by jeyk333** [patelmayankce/react-apple-login#17]
Below is my code, Please let me know, what i am doing wrong here. If i kept the default type, it gives me the code. But, i want token. I have tried by passing both modes fragment and form_type. But, getting the same error.

<AppleLogin
                  clientId={"client-id"}
                  redirectURI={"redirect-url"}
                  responseType={"id_token"}
                  responseMode={"fragment"}
                  render={(renderProps) => (
                    <button
                      onClick={renderProps.onClick}
                    >Apple</button>
                  )}
                />

**Comment by AdamBCo** [comment]
Any update on this issue? I’m experiencing a similar issue where specifying responseType as id_token causes authentication to fail.

**Comment by jeyk333** [comment]
> Any update on this issue? I’m experiencing a similar issue where specifying responseType as id_token causes authentication to fail.

Nope, still facing the same issue with the library

**Comment by marcin-wicha** [comment]
I had the same issue with only id_token, works with both code/id_token.
See below working code:
```jsx
<AppleLogin
       clientId={'client'}
       redirectURI={'https://example.com/endpoint'}
       scope={'name email'}
       responseType={'code id_token'}
       responseMode={'form_post'}
       render={renderProps => (
      <ButtonApple onClick={renderProps.onClick} type="button">
             <IconWrapper src={appleIcon}></IconWrapper>
            {t('button.apple')}
      </ButtonApple>)}
 />
```

**Comment by jeyk333** [comment]
I tried this too, but same error

**Comment by patelmayankce** [comment]
@jeyk333 , Follow this https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple#create-a-private-key-for-client-authentication
as I personally used the same package for our all projects and is works well. we follow the above steps for setup.

**Comment by jeyk333** [comment]
I have followed the same steps in the link. When I tried with default way its working. But, when i use the library with same details. other than code, I couldn't able to get anything.

**Comment by patelmayankce** [comment]
Let me share my code which works very well for me.

**Backend Code(Node JS)**

```
const {
  payload: { code, redirectUrl, scope },
} = request;

const privateKey = config.constants.APPLE_SSO.PRIVATE_KEY;
const token = JWT.sign({}, privateKey, {
  algorithm: 'ES256',
  audience: 'https://appleid.apple.com',
  subject: config.constants.APPLE_SSO.CLIENT_ID,
  expiresIn: '1h',
  keyid: config.constants.APPLE_SSO.KEY_ID,
  issuer: config.constants.APPLE_SSO.TEAM_ID,
});

const req = Wreck.request(
  'POST',
  `https://appleid.apple.com/auth/token`,
  {
    payload: querystring.stringify({
      grant_type: 'authorization_code',
      code,
      redirect_uri:
        redirectUrl || config.constants.APPLE_SSO.REDIRECT_URL,
      client_id: config.constants.APPLE_SSO.CLIENT_ID,
      client_secret: token,
      scope: scope || config.constants.APPLE_SSO.scope,
    }),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
  },
);
const res = await req.catch(async (err) => console.log(err));
const body = await Wreck.read(res);
```

**Front end code**

```
<AppleLogin
  {...{
    responseType: 'code',
    responseMode: 'form_post',
    clientId: clientId,
    redirectURI: redirectURI,
    scope: 'name',
    state: redirectUri,
  }}
  render={(renderProps) => (
    <button type="button" onClick={(e) => onAppleSSOClick(e, renderProps.onClick)}>
      <img src={iconApple} height={20} alt="Apple" />
      Apple
    </button>
  )}
/>
```

Let me know any more information do you need.

**Comment by kai4idps** [comment]
https://developer.apple.com/forums/thread/660531
