### ISSUE TITLE
UsePopup prop type

### ISSUE THREAD

**Issue by simonrajter** [patelmayankce/react-apple-login#20]
Hi,
i found an issue with the prop usePopup. In AppleLoginProps it is defined as type string, but the AppleLogin component expects a boolean value. The solution would be to change the type for usePopup inside AppleLoginProps to boolean.

**Comment by divyanshugarg36** [comment]
Hey, you can check out PR#22 for the fix of this issue

**Comment by patelmayankce** [comment]
@divyanshugarg36 , Thanks for your contributions released new version https://www.npmjs.com/package/react-apple-login/v/1.1.3
