### ISSUE TITLE
usePopup not working in Android web browser

### ISSUE THREAD

**Issue by rajoleanil75** [patelmayankce/react-apple-login#24]
I implemented the Apple login in my website using the following code and that work perfectly in desktop browser (like Chrome, Edge, Firefox, etc.) and iOS Safari browser, but when I open the site in android mobile browsers (i.e. Chrome, Edge, Firefox, etc.) then that popup is opening in a new tab (this does not issue because the sign in with google and LinkedIn also open in new tab) but when I fill up the information and continue then that popup/tab is not closed automatically and I'm not able to login using apple id.

Below is a snippet of my code
```
<AppleLogin
    clientId={CLIENT_ID}
    redirectURI={REDIRECT_URI}
    scope={"email"}
    responseType={"id_token"}
    responseMode={"form_post"}
    usePopup={true}
    callback={(data, err) => {
        if(data){
           //process data
            .
            .
        }
        else{
           // Error occurred while sign in
        }
      }
    }
    render={(renderProps) => (
      <Button onClick={renderProps.onClick}>
          <AppleIcon style={{fontSize: 18,}}/>
      </Button>
    )}
/>

```
and Screenshot of when I click on continue then nothing happen
![20210108_111952](https://user-images.githubusercontent.com/22848359/103979513-f2cd6c00-51a3-11eb-8b46-b6a91ec11007.jpg)

**Comment by phu0n9** [comment]
hi, have you found the solution for this yet?

**Comment by rajoleanil75** [comment]
> hi, have you found the solution for this yet?

No, we removed login with apple id from website

**Comment by phu0n9** [comment]
You can use redirect, i solved this problem few weeks ago, it turned out Android webview prohibit popup and it is better to use redirect method instead. Hope it would help.

**Comment by parttiez** [comment]
But, isn't redirect require a server?
