### ISSUE TITLE
Found: react@17.0.2 Could not resolve dependency: react@"^15.0.0 || ^16.0.0" from react-apple-login@1.1.3

### ISSUE THREAD

**Issue by leopucci** [patelmayankce/react-apple-login#30]
Does not work with latest versions
![image](https://user-images.githubusercontent.com/38509299/130326820-6efe8884-89c1-4b9a-a51c-ccb8926f3565.png)

**Comment by leopucci** [comment]
https://github.com/patelmayankce/react-apple-login/pull/31

**Comment by patelmayankce** [comment]
@leopucci thanks for PR.

**Comment by leopucci** [comment]
Anytime @patelmayankce =)
