### ISSUE TITLE
using usePopup true have two times request

### ISSUE THREAD

**Issue by tanz98** [patelmayankce/react-apple-login#38]
Hello i found bugs when login apple with usePopup={true} in real device, if in desktop google chrome browser is fine. but when i try in safari desktop browser & safari ios, the library not works fine. Usepopup request 2 times so  when i second times login i cannot get name & email in the first time login. how to solve this?

**Comment by patelmayankce** [comment]
Hi @tanz98 , This is Apple’s default behavior. You will only get email and name very first time. Where you have to save it in backend. At library level we can’t fix this.
