### ISSUE TITLE
how could I get userId besides of the auth token?

### ISSUE THREAD

**Issue by markmoomoo** [patelmayankce/react-apple-login#5]
I can only get my auth token from the redirect uri
     that is. my redirect uri is https://foo.bar.com?code=<authCode>
is there a way I can also get the userId from it?
 https://foo.bar.com?code=<authCode>& userId=[userIdcallback]
thank you

**Comment by patelmayankce** [comment]
Hi @markmoomoo , you can follow the instruction on how to implement Apple SSO further [here](https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple#create-a-private-key-for-client-authentication) 

Apple can only get you code and using the code you have to make an API call to Apple to get detailed information of the user.
